---
- hosts: 127.0.0.1
  connection: local
  user: vagrant
  sudo: yes
  tasks:
    - name: install apt packages
      apt: name={{ item }} update_cache=yes
      with_items:
      - git
      - tmux
      - zsh
      - htop
      - vim

    - name: clone Prezto
      git: repo=https://github.com/sorin-ionescu/prezto.git dest=/home/vagrant/.zprezto

    - name: copy zsh setting files
      command: /bin/sh /vagrant/ansible/copy_zsh_setting_file.sh

    - name: default shell set to zsh
      command: chsh -s /usr/bin/zsh vagrant

    - name: change owner
      command: chown -R vagrant:vagrant /home/vagrant/

    - name: zpreztorc modified
      command: /bin/sh /vagrant/ansible/modified_zsh_setting_files.sh


